title: ScaryRawr
email: michael.wallio@outlook.com
description: >-
  Ramblings of a computer nut kupo...
baseurl: ""
url: ""
twitter_username: scaryrawr
github_username: scaryrawr

theme: minima
plugins:
  - jekyll-feed

# Serving
port: 4000
host: localhost
